spring:
  application:
    name: OrganizerService

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: ***
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      format_sql: true
      show_sql: false
      properties:
        hibernate:
          highlight_sql: true
          format_sql: true
          jdbc:
            lob:
              non_contextual_creation: true
          type:
            trace: true

logging:
  level:
    root: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE